PATH_MODEL : "./models/BioBert1E"
PATH_LOGS : "./logs/BioBert1E.txt"
PATH_VALID_LOGS : "./logs/BioBert1EValide.txt"
MODEL : "dmis-lab/biobert-large-cased-v1.1-squad"
MODE : "Bert"
PATH_DATASET : "./data/"
DEVICE : "cuda"
WEIGHTED: True
FULL_FINETUNING: True
BATCH_SIZE : 8
EPOCHS : 1
PATIENCE : 1
LR: 0.00003