PATH_MODEL : "./models/BertBase"
PATH_LOGS : "./logs/BertBase.txt"
PATH_VALID_LOGS : "./logs/BertBaseValid.txt"
MODEL : "google-bert/bert-base-uncased"
MODE : "Bert"
PATH_DATASET : "./data/"
DEVICE : "cuda"
WEIGHTED: True
BATCH_SIZE : 16
EPOCHS : 10
PATIENCE : 2
LR: 2e-5