PATH_MODEL : "./models/BertBase1E"
PATH_LOGS : "./logs/BertBase1E.txt"
PATH_VALID_LOGS : "./logs/BertBase1EValid.txt"
MODEL : "google-bert/bert-base-uncased"
MODE : "Bert"
PATH_DATASET : "./data/"
DEVICE : "cuda"
WEIGHTED: True
FULL_FINETUNING: True
BATCH_SIZE : 16
EPOCHS : 1
PATIENCE : 1
LR: 0.00003