PATH_MODEL : "./models/BioBert"
PATH_LOGS : "./logs/BioBert.txt"
PATH_VALID_LOGS : "./logs/BioBertValid.txt"
MODEL : "dmis-lab/biobert-v1.1"
MODE : "Bert"
PATH_DATASET : "./data/"
DEVICE : "cuda"
WEIGHTED: True
BATCH_SIZE : 16
EPOCHS : 10
PATIENCE : 2
LR: 0.00002